### ISSUE TITLE
Question - is there a way to control the background color of the tutorial layer?

### ISSUE THREAD

**Issue by tidharnitzan** [RafaelBarbosatec/tutorial_coach_mark#1]
HI, very good work!
would really like a way to control the target focus background color (now it's kind of red).

**Comment by RafaelBarbosatec** [comment]
Thank you!
Yes, it is possible to control the background color, there is a variable that you can pass called "colorShadow". And you can also control the opacity with the variable "opacityShadow".

**Comment by tidharnitzan** [comment]
Cool.Thanks.
