### ISSUE TITLE
finish tutorial when clicking the overlay?

### ISSUE THREAD

**Issue by galvanu** [RafaelBarbosatec/tutorial_coach_mark#102]
I want to close the tutorial when clicking the overlay but unfortunately I can't find a way to access the `finish `method from the `onClickOverlay `callback.
Am I missing something?

**Comment by galvanu** [comment]
Yes, tried this sample but unfortunately it doesn't work.
In addition I tried just to print inside the onClickOverlay handler but it looks like it also doesn't work:

```
TutorialCoachMark(
        context,
        targets: targets,
        colorShadow: Colors.blueGrey,
        hideSkip: true,
        paddingFocus: 10,
        opacityShadow: 0.9,
        onClickTarget: (target) {
         print('onClickTarget');
        },
        onClickOverlay: (target) {
          print('onClickOverlay');
        }
      ).show();
```

@d-wolf - What an I missing?

**Comment by bakatsuyuki-hm** [comment]
@galvanu 
Maybe you can solve the problem by adding
`enableOverlayTab: true,`
to TutorialCoachMark.

**Comment by UlyssesAlves** [comment]
Actually one should set property `enableOverlayTab `to true in the `TargetFocus `object while creating the targets, not on the `TutorialCoachMark `object itself.
