### ISSUE TITLE
Feature request, possibility to display a message/screen when the tutorial is started

### ISSUE THREAD

**Issue by eripe970** [RafaelBarbosatec/tutorial_coach_mark#105]
Background: I'm running a tutorial directly when the users have completed the onboarding flow in my app. It would be nice if I could present them with a message/screen to say that there will be a tutorial of the functionality in the app, like a start screen. 

Thanks for a nice package!

**Comment by RafaelBarbosatec** [comment]
The idea is be a package minimalist, that show a guided overlay tutorial. This implementation of screen pre-tutorial you can do own easily
