### ISSUE TITLE
Is it possible to create a TargetFocus without target?

### ISSUE THREAD

**Issue by masushin** [RafaelBarbosatec/tutorial_coach_mark#107]
Is it possible to create a TargetFocus without a target?

In normal steps, we use a coach mark, 
but in some steps, the Widget that should be the target for the coach mark does not exist on the current screen.

In this case, I would like to display only the text widget for explain without specifying a target. 

Is there any way for it ?

**Comment by ScottLee97** [comment]
Hi, I'm also looking to create a targetfocus without a target but haven't got any luck. Have you found a workaround?

**Comment by quickratio** [comment]
Just use an empty widget e.g. a container?

**Comment by masushin** [comment]
sorry for late response.

I found workaround.
Makes TargetForcus with the following parameters,

```
focusAnimationDuration: Duration.zero,
pulseVariation: Tween(begin: 1, end: 1),
```

Depending on the position of the empty widget,it may need to custom the position of the text widget, it seems good.

( the 3rd step is it. )

![output](https://user-images.githubusercontent.com/18723885/156471953-a30bba9a-0424-48b1-9e73-4c0203b530a5.gif)

I am a little concerned about the continuity with the one previous TargetFocus..
