### ISSUE TITLE
The tutorial repeats itself if I runs it more than 1 time in the same page without closing the page.

### ISSUE THREAD

**Issue by EcenurOzal** [RafaelBarbosatec/tutorial_coach_mark#112]
If I onPressing an icon to run the tutorial one time in the same page.It works great. But when I run the icon again without closing tthe page the tutorial repeats itself. If I click the icon for examle 4 time, the tutorial runs 4 times. How can I fix it. 

`
IconButton(
icon: Icon(
Icons.star,
color: Colors.white,
size: 26.0,
),
onPressed: () {
buildTutorialList(context);
startTutorialMode();
},`

**Comment by EcenurOzal** [comment]
`void startTutorialMode() {
int counter=0;
if(counter==0)
{
_scrollController.animateTo(_scrollController.position.minScrollExtent,duration: Duration(milliseconds:1),curve: Curves.easeOut);
}
TutorialCoachMark(
context,
targets: targetList,
onClickTarget: (target) {
setState(() {
counter++;
print(counter);
        if(counter==1)
      {
      _scrollController.animateTo(_scrollController.position.maxScrollExtent,duration: Duration(milliseconds:500),curve: Curves.ease);
      }    
      else if(counter==2)
      {
      _scrollController.animateTo(_scrollController.position.maxScrollExtent,duration: Duration(milliseconds:500),curve: Curves.ease);
      }
    });},
)..show();
}`

`buildTutorialList(BuildContext context) {
targetList.addAll(
[
TargetFocus(
identify:"1",
shape: ShapeLightFocus.RRect,
radius: 10,
keyTarget: nameKey,
contents: [
TargetContent(
align: ContentAlign.bottom,
child: Column(
children: [
Text(
Languages.of(context).guideTaskName,
textWidthBasis: TextWidthBasis.longestLine,
style: TextStyle(
color: Colors.white,
fontWeight: FontWeight.bold,
fontSize: 17,),),],),),],),
TargetFocus(
identify:"2",
shape: ShapeLightFocus.RRect,
radius: 10,
keyTarget: addTaskKey,
contents: [
TargetContent(
align: ContentAlign.bottom,
child: Column(
children: [
Text(
Languages.of(context).guideTaskName,
textWidthBasis: TextWidthBasis.longestLine,
style: TextStyle(
color: Colors.white,
fontWeight: FontWeight.bold,
fontSize: 17,),),],),),],),
TargetFocus(
identify: "3",
shape: ShapeLightFocus.RRect,
radius: 10,
keyTarget: saveAsTemplateKey,
contents: [
TargetContent(
align: ContentAlign.bottom,
child: Column(
children: [
Text(
Languages.of(context).guideTaskName,
textWidthBasis: TextWidthBasis.longestLine,
style: TextStyle(
color: Colors.white,
fontWeight: FontWeight.bold,
fontSize: 17,),),],),),],),],);}
`

**Comment by RafaelBarbosatec** [comment]
This package not provide management of times that show. You need create you own implementation using something that can persist data in device like SharedPreference.
