### ISSUE TITLE
Keep Overlay during all futorial

### ISSUE THREAD

**Issue by GreyHat147** [RafaelBarbosatec/tutorial_coach_mark#117]
How can I disable every transition on each `tutorial.next` action, just I want maintain the black overlay during the whole tutorial flow?

**Comment by RafaelBarbosatec** [comment]
Hi @GreyHat147 !

You can set animation duration to zero. like thate:

``` dart

 TutorialCoachMark(
      targets: _createTargets(),
      focusAnimationDuration: Duration.zero,
      unFocusAnimationDuration: Duration.zero,
);

```
