### ISSUE TITLE
Feature Request: Be able to make the tutorial show only once 

### ISSUE THREAD

**Issue by davidaodejobi** [RafaelBarbosatec/tutorial_coach_mark#123]
I am trying to make the tutorial show up only once

If the method is called inside the initState method, it keeps showing every time I move to that screen.

**Comment by RafaelBarbosatec** [comment]
Hi @davidaodejobi !
 The idea is that @Faamica wrote here. It’s not issue about the package.

**Comment by davidaodejobi** [comment]
Yeah I thought of that too, and that was what I later used. But I was thinking that it'll be cool if that was added to the package 

Thanks for responding 💕
