### ISSUE TITLE
tutorialCoacmark next  method always trigerred when tapped/pressed a widget  having Global Key on Target Content 

### ISSUE THREAD

**Issue by ramaagusdwi** [RafaelBarbosatec/tutorial_coach_mark#124]

**Comment by RafaelBarbosatec** [comment]
Hi @ramaagusdwi 
 Thanks for report.
Could you give me more information. I don't understand very well this issue.

**Comment by jawadali99** [comment]
How can i trigger target focus to other while clicking on widgets which are in target content

**Comment by jawadali99** [comment]
rather than clicking on focused area

**Comment by RafaelBarbosatec** [comment]
There is example this behavior ur! In this project. You can do next or previous.
In `TargetContent`:`builder `:
call `controller.previous();` or `controller.next();`
