### ISSUE TITLE
Disable the bouncing animation of the TargetFocus

### ISSUE THREAD

**Issue by pratik97179** [RafaelBarbosatec/tutorial_coach_mark#131]
I want to disable the bouncing effect that we see on the `TargetFocus`. I want the `TargetFocus` to remain static/to not animate. Is there any way to do that?

**Comment by RafaelBarbosatec** [comment]
Hi @pratik97179 !
Yes, it's possible. You can set pulseEnable to false

**Comment by ardeshir-33033** [comment]
pulseEnable only disables the pulse animation of the widget that the global key is given,
but the bouncing animation is for the CoachWidget that shows the tutorial and it wont stop going up and down (Bouncing) with pulseEnable.

any idea?
