### ISSUE TITLE
Avoid/block target tab for 2 seconds, after previous target tab

### ISSUE THREAD

**Issue by adschi** [RafaelBarbosatec/tutorial_coach_mark#134]
Hey there, love the package and trying to implement a cool tutorial with it.. But here is my problem:

When user presses quickly and many times on targets, it likely to crash the animation between animating.. How can I block the user's gesture for like 2 seconds after he presses the first target?  After 2secs enable the press again and so on.. 
When I create the TutorialCoachMark with the targets, the enableTargetTab Option in the TargetFocus won´t update anymore..

Thank you very much. :)

**Comment by RafaelBarbosatec** [comment]
Hi @adschi ! Thanks so much!
I’m sorry, i don’t can reproduce this problem.

**Comment by sevenzees** [comment]
I'm also experiencing this problem in my app. I don't see the problem when running the example code though.

**Comment by sevenzees** [comment]
In my app, if the user taps a bunch of times (specifically if they tap while the tutorial is between the unfocus animation and the next focus animation), the best case scenario is that the tutorial exits. The worst case is that sometimes it corrupts the state and I need to restart the app.

**Comment by sevenzees** [comment]
It would be very useful to be able to block taps during the animation between tutorial steps. @adschi, did you ever figure out how to do this?

**Comment by adschi** [comment]
@sevenzees Yes, i fixed it with an extra IgnorePointer Widget Overlay, which i set to ignore pointer for 2 seconds after every next step click.

**Comment by sevenzees** [comment]
@adschi Thanks for pointing me in the right direction. For anyone else with the same issue, here's the code I used to "fix" it. I just called this every next step click:

`static void showOverlay(BuildContext context) {
    OverlayState overlayState = Overlay.of(context);

    OverlayEntry overlayEntry = OverlayEntry(
      builder: (context) {
        return Positioned.fill(
          child: Listener(
            behavior: HitTestBehavior.opaque,
            child: Container(),
          ),
        );
      },
    );

    if (kDebugMode) {
      print('Applying no-tap overlay');
    }

    overlayState.insert(overlayEntry);
    Future.delayed(const Duration(seconds: 2))
        .whenComplete(() => overlayEntry.remove());
  }`
