### ISSUE TITLE
issues with tutorial_coach_mark and showModalBottomSheet 

### ISSUE THREAD

**Issue by desmeit** [RafaelBarbosatec/tutorial_coach_mark#135]
If I have an `showModalBottomSheet` which is open along the keyboard with `isScrollControlled: true` it is reloading continuous the whole app behind the bottom sheet during the animation. It only occurs when the tutorial coach has been run previously.

Is this a bug?

**Comment by RafaelBarbosatec** [comment]
I think that its not a problem about `tutorial_coach_mark `
