### ISSUE TITLE
Forward click to the actual widget behind overlay

### ISSUE THREAD

**Issue by large** [RafaelBarbosatec/tutorial_coach_mark#136]
Great class! It has helped me explaining my app for many users so far.

There have been some feedback that the user want the "action" to happen when clicking forward in tutorial.
So if you are in the tutorial and explain that when you click this button, that will happen, it actually should be executed.
Is that straight forward?

For example I have a DropdownButton() widget that I want to trigger. When the user have enabled a function I will continue the tutorial.
Any toughts?

Edit:
If I wrap AnimatedFocusLight() with IgnorePointer() I get the behaviour I would expect on the overlay.
https://github.com/RafaelBarbosatec/tutorial_coach_mark/blob/c6c0186bf1bed51bc959a984e297e6dae92c6276/lib/src/widgets/tutorial_coach_mark_widget.dart#L69-L101

But when using the same technique in the TargetFocus() objects, I cannot get it to work.

**Comment by large** [comment]
Just came over this widget for such behavior: https://pub.dev/packages/highlighter_coachmark

**Comment by dvagala** [comment]
+1 this feature would be great. Sadly the `highlighter_coachmark` seems not maintained anymore

**Comment by erperejildo** [comment]
> +1 this feature would be great. Sadly the `highlighter_coachmark` seems not maintained anymore

so this right now is not possible at all? I think this feature is not only great but also mandatory in a package like this

**Comment by erperejildo** [comment]
any update on this?
