### ISSUE TITLE
TargetFocus(unFocusAnimationDuration) doesn't exist?

### ISSUE THREAD

**Issue by AnthonyZ71** [RafaelBarbosatec/tutorial_coach_mark#138]
The documentation [here](https://pub.dev/documentation/tutorial_coach_mark/latest/) describes TargetFocus as having a parameter called unFocusAnimationDuration which is the "other side" of the focusAnimationDuration parameter.

The [master branch](https://github.com/RafaelBarbosatec/tutorial_coach_mark/blob/57a64dc05dd9de3980f603f2e3c4fdec63bf1e47/lib/src/target/target_focus.dart#L7), the [develop branch](https://github.com/RafaelBarbosatec/tutorial_coach_mark/blob/d615bb629a4b0b0a8f0a64061d38ee414729cf99/lib/src/target/target_focus.dart#L6),  and what is released as part of 1.2.4 doesn't include this parameter.

This *seems* to be a nice way to handle items that would take multiple screens to describe...  Make the first TargetFocus give the first part of the information, with an unfocus duration of 0.01ms while the next TargetFocus with the rest of the information would have a focus duration of 0.01ms.

[This commit](https://github.com/RafaelBarbosatec/tutorial_coach_mark/commit/1278b9edfeab92bc59ded92d517e866abd22a859) back in April of 2022 seems to have added documentation for [this commit](https://github.com/RafaelBarbosatec/tutorial_coach_mark/commit/ed7e88c6c82bd6ff680bbc2f1e25ba5780585925) but this is on the TutorialCoachMark constructor, not the TargetFocus constructor.  It would make sense that the TutorialCoachMark would have the default focusAnimationDuration and unFocusAnimationDuration while the TargetFocus would also have the durations so that you could override them for specific TargetFocus elements.  Not sure if this is a bug or a new feature request.

**Comment by AnthonyZ71** [comment]
I've not looked properly at the code at all.  Is this as simple as modifying TargetFocus to have the parameter and field, and then modifying these places to make use of the field?

- https://github.com/RafaelBarbosatec/tutorial_coach_mark/blob/57a64dc05dd9de3980f603f2e3c4fdec63bf1e47/lib/src/widgets/animated_focus_light.dart#L282
- https://github.com/RafaelBarbosatec/tutorial_coach_mark/blob/57a64dc05dd9de3980f603f2e3c4fdec63bf1e47/lib/src/widgets/animated_focus_light.dart#L426

**Comment by RafaelBarbosatec** [comment]
Available in 1.2.6 version
