### ISSUE TITLE
NoSuchMethodError: The getter 'offset' was called on null.

### ISSUE THREAD

**Issue by grandpa-guru** [RafaelBarbosatec/tutorial_coach_mark#14]
NoSuchMethodError: The getter 'offset' was called on null.
Receiver: null
Tried calling: offset

Exception details:
```
Library: package:tutorial_coach_mark/animated_focus_light.dart,
Line: 191,
Method: _nextFocus.<fn>,
Class: _AnimatedFocusLightState
```

**Comment by diceku** [comment]
do you have any plans to merge this fix version? @grandpa-guru @RafaelBarbosatec

**Comment by grandpa-guru** [comment]
> do you have any plans to merge this fix version? @grandpa-guru @RafaelBarbosatec

If @RafaelBarbosatec has some free time to merge it I'll be more than happy to create a pull request.

**Comment by diceku** [comment]
@RafaelBarbosatec I appreciate if you check on this pull request, Im having same error.
