### ISSUE TITLE
skipText is not visible in version 1.2.6

### ISSUE THREAD

**Issue by volgin** [RafaelBarbosatec/tutorial_coach_mark#147]
After upgrading to version 1.2.6 I noticed that skipText is no longer visible. Changing position, size, color, etc. has no effect.

Workaround: downgrade to version 1.2.5.

**Comment by CodeRedDev** [comment]
I'm using 1.2.4 and I experience this too. This should definitely be optional.

**Comment by felipecastrosales** [comment]
In 1.2.7 has the `showSkipInLastTarget` property. Check, please @volgin.

**Comment by volgin** [comment]
I just checked. There is no such property. And I don't see it committed in the code.

**Comment by felipecastrosales** [comment]
@volgin, if you check changelog has this information.

![image](https://user-images.githubusercontent.com/59374587/224851196-6a949067-17ab-44b0-bc72-424b63b151bf.png)

I tested and works as expected.

**Comment by volgin** [comment]
Yes, this is the version that I am trying. There is no such property.

**Comment by felipecastrosales** [comment]
@volgin, see [this](https://github.com/RafaelBarbosatec/tutorial_coach_mark/blob/master/lib/tutorial_coach_mark.dart#L35).

Run: `flutter clean && flutter pub cache repair && flutter pub get` in your terminal.

**Comment by felipecastrosales** [comment]
And check if your are using `1.2.7` version, its much important.

**Comment by volgin** [comment]
I did run Flutter clean, although it has no effect on the source code. And I did check that I have version 1.2.7.

**Comment by felipecastrosales** [comment]
> I did run Flutter clean, although it has no effect on the source code. And I did check that I have version 1.2.7.

Well again, make sure it's on version `1.2.7` that will have the property and you can use it. 

Also, try restarting the IDE to check if it's not an analyzer bug.

**Comment by volgin** [comment]
<img width="425" alt="Screen Shot 2023-03-13 at 9 42 58 PM" src="https://user-images.githubusercontent.com/297748/224870595-bf76766f-2d0a-4f1b-bfe7-934c668e05e7.png">

**Comment by volgin** [comment]
Repaired cache, restarted IDE, still the same source code:

<img width="579" alt="Screen Shot 2023-03-13 at 9 46 07 PM" src="https://user-images.githubusercontent.com/297748/224870941-7dc6ab0c-ec9b-476c-bcd9-9e6bcb8ecf6a.png">

**Comment by felipecastrosales** [comment]
@volgin yes, that's it. 
Instead of: `tutorial_coach_mark: 1.2.5`.
Uses: `tutorial_coach_mark: ^1.2.7`.

⚠️⚠️⚠️ Important, use `1.2.7` or higher.

**Comment by volgin** [comment]
Yes, that's what I did.

**Comment by volgin** [comment]
I am testing with ^1.2.7

**Comment by volgin** [comment]
In version 1.2.8 this method appeared.
