### ISSUE TITLE
onClickOverlay does not fire

### ISSUE THREAD

**Issue by volgin** [RafaelBarbosatec/tutorial_coach_mark#148]
In version 1.2.5 onClickOverlay does not fire. onClickTarget fires as expected.

**Comment by Cotspheer** [comment]
Had the same issue. Set "enableOverlayTab: true" on TargetFocus. It's disabled by default. Also make sure to set it on all TargetFocus that should have the behavior enabled.

**Comment by volgin** [comment]
Unfortunately, it does not help. I looked at the source code - it explicitly hides the skip widget when the last target is being displayed.

**Comment by RafaelBarbosatec** [comment]
It's work well in version `1.2.8`. just set `enableOverlayTab` true in your `TargetFocus`
