### ISSUE TITLE
Method 'insert' cannot be called on 'OverlayState?'

### ISSUE THREAD

**Issue by huynhmytuan** [RafaelBarbosatec/tutorial_coach_mark#150]
After I update to the latest version, have an error with null safety on this function at line 95:
```dart
void show({required BuildContext context, bool rootOverlay = false}) {
    Future.delayed(Duration.zero, () {
      if (_overlayEntry == null) {
        _overlayEntry = _buildOverlay(rootOverlay: rootOverlay);
        Overlay.of(context, rootOverlay: rootOverlay).insert(_overlayEntry!);
      }
    });
  }
```

Please take a look. Thank you.

**Comment by lrincon-lealco** [comment]
Change line 95 to the following code Overlay.of(context, rootOverlay: rootOverlay)?.insert(_overlayEntry!);.

I'm trying to upload a PR to solve the problem but I don't have permissions.
