### ISSUE TITLE
add semantics features to TutorialCoachMarkWidget

### ISSUE THREAD

**Issue by pga61** [RafaelBarbosatec/tutorial_coach_mark#156]
Because of wrapping skipWidget with IgnorePointer widget without [ignoringSemantics] argument you suppress semantic features. Is it possible to add [ignoringSemantics] argument to TutorialCoachMarkWidget.

Thanks a lot.

**Comment by RafaelBarbosatec** [comment]
It's will be available in the next release. I'm sorry for late.

**Comment by pga61** [comment]
No problem! Great news 👍
Thanks a lot
