### ISSUE TITLE
issue in pulseEnable

### ISSUE THREAD

**Issue by devbrisk** [RafaelBarbosatec/tutorial_coach_mark#165]
When pulseEnable sets to false, imageFilter ignored.
please fix it.

**Comment by RafaelBarbosatec** [comment]
Hi @devbrisk !
Thanks for report it.
Fixed in version `1.2.11`

**Comment by masewo** [comment]
Was it released from branch https://github.com/RafaelBarbosatec/tutorial_coach_mark/tree/develop?
