### ISSUE TITLE
Different colorShadow for each targetFocus?

### ISSUE THREAD

**Issue by topex-psy** [RafaelBarbosatec/tutorial_coach_mark#17]
I want to set different background color for each `TargetFocus`. How can I achieve this?

**Comment by RafaelBarbosatec** [comment]
Good ideia!
Thanks for suggestion!
I will go improve the package for support this.

**Comment by Tushtisachdeva01** [comment]
How to set a different background colour for each TargetFocus?

**Comment by RafaelBarbosatec** [comment]
will be available in version 0.4.0
