### ISSUE TITLE
Close programatically

### ISSUE THREAD

**Issue by pcegarra** [RafaelBarbosatec/tutorial_coach_mark#19]
Could be great close the tutorial programatically, I think now is not possible.

**Comment by RafaelBarbosatec** [comment]
Hi @pcegarra ! Tell me more about this. close with some downtime?

**Comment by pcegarra** [comment]
No, just add the option to close from other widget, like open it

**Comment by RafaelBarbosatec** [comment]
Got it, i will go think in way to add a 'Controller' for this.

**Comment by RafaelBarbosatec** [comment]
you can save the instance of `TutorialCoachMark` and call the method` finish` or `skip`
