### ISSUE TITLE
How do show tutorials on pages compiled from several widgets ?

### ISSUE THREAD

**Issue by tidharnitzan** [RafaelBarbosatec/tutorial_coach_mark#2]
my view is compiled from several widgets. how do I pass the global key and make it available to different views?
If you can create more advanced example it would be great.
Thanks.

**Comment by RafaelBarbosatec** [comment]
I also had this case on a personal project. you'll have to figure out a strategy for that. You can send Globalkey by creating the widget, or each widget has its own tutorial creating a method to display it, so when you want it to display your tutorial you call this method.

**Comment by tidharnitzan** [comment]
got it. thanks.

**Comment by SalahAdDin** [comment]
@tidharnitzan how did you handle this?

**Comment by tidharnitzan** [comment]
this was a while ago...
AFAIK i create a key for each widget and for different pages I had different coach loaded.

**Comment by SalahAdDin** [comment]
> this was a while ago...
> AFAIK i create a key for each widget and for different pages I had different coach loaded.

So, you created a tutorial for each widget you need to, right?
