### ISSUE TITLE
TargetPosition settings

### ISSUE THREAD

**Issue by dmckminard** [RafaelBarbosatec/tutorial_coach_mark#21]
Hello!
I'd like to implement this cool plugin, but I've got few questions.

The key-target that I want to target is in another page, how can I target it in my main page?
I would have liked to curl this using the position Target, but what arguments should we give it? Could it be possible to have an example?

**Comment by jeremySrgt** [comment]
Hi,
i'm using Target position in my project, here is the code :
`targetPosition: TargetPosition(Size(20.0, 20.0),Offset(10.0, 10.0)),`
which focus the left corner of the app with size of 20x20

don't forget to import 
`import 'package:tutorial_coach_mark/target_position.dart';`

**Comment by SalahAdDin** [comment]
I'm getting the next error using `TargetPosition`:
```
[  +35 ms] I/flutter (18813): TutorialCoachMark (ERROR): It was not possible to obtain target position.
[+8639 ms] I/flutter (18813): TutorialCoachMark (ERROR): It was not possible to obtain target position.
```
