### ISSUE TITLE
Focus click on the content, not the all view

### ISSUE THREAD

**Issue by Victor-Dev77** [RafaelBarbosatec/tutorial_coach_mark#28]
I would like to be able to click on the content and not on the view before moving on to the next Target.

I don't know if that's a good thing but I comment the `_tapHandler()` method in widget.streamTap in `initState()`. 

Then, I replace InkWell Widget by GestureDetector and add `onTapDown` listener and add `_tapHandler()` method.

Finally, I detect the hitbox between `TapDownDetails` Offset (dx, dy) and the `targetPosition` param.

I don't know if it's well but, it's work !
But, sometimes, I've error of `TargetPosition`: ("ERROR: Não foi possivem oter informações da KEY")

I don't know if it's about to my modifications or because I've FutureBuilder despite `WidgetsBinding.instance.addPostFrameCallback` and the `Future.delayed`.

If you have a reponse, thanks a lot ! :)

**Comment by aldwnesx** [comment]
Any updates? I am trying to do what you mentioned

**Comment by stephenjen** [comment]
Hi @Victor-Dev77 , I know this was a long time ago but I'm having the same problem where my screen is built with FutureBuilder.  Calling createTutorial() and showTutorial() within SchedulerBinding.instance.addPostFrameCallback does not work, but setting Future.delayed to something like 5 seconds within initState does work for me.
