### ISSUE TITLE
Adapt for web

### ISSUE THREAD

**Issue by Vove7** [RafaelBarbosatec/tutorial_coach_mark#31]
Inconsistent performance on Android and Web：

- On Web:

![image](https://user-images.githubusercontent.com/25018573/82402838-fb93f500-9a8f-11ea-9f0a-66be9563b7e7.png)

- On Android
![C) OKNC(`KU)SKD1Q5U2BBU](https://user-images.githubusercontent.com/25018573/82402928-3c8c0980-9a90-11ea-8864-37008c9a4ae9.jpg)

**Comment by RafaelBarbosatec** [comment]
There is a problem with the Flutter Web canvas. I'm trying to get around this problem

**Comment by RafaelBarbosatec** [comment]
Hi @Vove7 !
Supporte for a web added in 1.1.0 version!
