### ISSUE TITLE
GlobalKey element offset

### ISSUE THREAD

**Issue by franskjv** [RafaelBarbosatec/tutorial_coach_mark#33]
Hi, I'm trying to use the package but every element I use a Global key,
 the highlight appears below that element: (I wanted the highlight on the kebab bottom)

<img width="443" alt="Screen Shot 2020-06-12 at 15 31 00" src="https://user-images.githubusercontent.com/4266955/84535378-15f17500-acc2-11ea-908b-cd5153e590c4.png">

I'm using the Global Key in my PopupMenuButton and keyTarget on the plugin call.

```
keyTarget: key,
```

Any hint what am I doing wrong?

Thanks in advance.

**Comment by CalHoll** [comment]
I'm encountering the same issue, for me it's also below the element I've assigned the global key to, @franskjv  did you find a resolution? 

Right now I've just been hard-coding positions but it get's complicated with some dynamically positioned widgets.

**Comment by RafaelBarbosatec** [comment]
Hi @franskjv ! 

this problem still continue? Doing some tests, I realized that you are focusing correctly

```
 return Scaffold(
      appBar: AppBar(
        actions: <Widget>[
          IconButton(
            // key: keyButton1,
            icon: Icon(Icons.add),
            onPressed: () {},
          ),
          PopupMenuButton(
            key: keyButton1,
            icon: Icon(Icons.view_list, color: Colors.white),
            itemBuilder: (context) => [
              PopupMenuItem(
                child: Text("Is this"),
              ),
              PopupMenuItem(
                child: Text("What"),
              ),
              PopupMenuItem(
                child: Text("You Want?"),
              ),
            ],
          )
        ],
      ),
```

**Comment by ToniTornado** [comment]
When you open the tutorial in a page that is pushed to the stack with animation, the position from the referenced widget is not yet the final position after the navigation animation. The offset depends on the direction the page is pushed. You can delay execution of `TutorialCoachMark(...).show()` by a value that is higher than the page transition duration to make it work.

**Comment by CalHoll** [comment]
Delaying didn't change anything for me. I'm currently working around it by setting a hard-coded height from the top of the screen but this is far from an ideal solution. I've had to use some creative math to figure out the placement of some elements.

**Comment by CalHoll** [comment]
So after a little digging I was able to identify the cause of this offset. It's the use of **SafeArea**, I use it near the top of my widget tree, and if I remove it the offset issue goes away (but my layout gets messed up).
