### ISSUE TITLE
Restore click to progress anywhere functionality

### ISSUE THREAD

**Issue by tubbytoad42** [RafaelBarbosatec/tutorial_coach_mark#35]
Since version 0.4.0, to progress through the tutorial screens the user must click the target itself on each screen. Prior to this, the functionality was clicking anywhere to progress. I am interested in adding a feature to optionally re-enable this functionality. For example, a boolean flag that enables the old click to progress feature would be optimal.

**Comment by brizaldi** [comment]
there's `enableOverlayTab` property inside `TargetFocus`, maybe you need to check that

**Comment by tubbytoad42** [comment]
This is exactly what I was looking for, apologies for missing it before.
