### ISSUE TITLE
Using with internationalization

### ISSUE THREAD

**Issue by degloff** [RafaelBarbosatec/tutorial_coach_mark#37]
Using tutorial_coach_mark with some internationalization support poses some issues. 

It seems to be required that initTargets is called in the initState function. 
But then calling the internationalization usually requires the context. 

Like this one: `S.of(context).`

```
    tutorialTargets.add(
        TargetFocus(
            identify: "id",
            keyTarget: widget.keys['xyz'],
            enableOverlayTab: true,
            contents: [
              ContentTarget(
                  child: Container(
                    child: Text(S.of(context).someText, style: largeTitleTextStyle),
                  )
              )
            ]
        )
    );
```

i suggest you change you setup to use AfterLayoutMixin and move the init of the targets to

```
  @override
  void afterFirstLayout(BuildContext context) {
    if (showTutor) {
      initTargets();
      Future.delayed(Duration(milliseconds: 100), () {
        showTutorial();
      });
    }
  }
```

**Comment by EducatedDeer** [comment]
recently added tutorial_coach_mark to my app but I am also worried about this.
how can we use context inside ContentTargets so that we can translate the text?

**Comment by RafaelBarbosatec** [comment]
Hi @degloff ! You can start targets in the method together with `TutorialCoachMark` to ensure that there is context or the suggestion from @EducatedDeer is cool.
