### ISSUE TITLE
Click to progress not only in target

### ISSUE THREAD

**Issue by Vitor-Bukovitz** [RafaelBarbosatec/tutorial_coach_mark#38]
I was using the version 0.3.0 and on 0.4.0 you changed the package with this **`Click to progress only in target`**, is there a way to disable it? I want my users to click anywhere in the screen and progress with the tutorial. I would be nice maybe a boolen like **`onlyTargetProgress`**, so then developers can set it.

**Comment by EducatedDeer** [comment]
there is a bool "enableOverlayTab: true"
but it doesn't progress when we tap on the texts, only when we tap on the spaces.
Sometimes the screen is filled with text when there are many things to explain.

**Comment by RafaelBarbosatec** [comment]
As mentioned by @EducatedDeer  just configure `TargetFocus` using` enableOverlayTab` and `enableTargetTab`
