### ISSUE TITLE
Web: PersistedOffset: is in an unexpected state.

### ISSUE THREAD

**Issue by chentianxin** [RafaelBarbosatec/tutorial_coach_mark#41]
PersistedOffset: is in an unexpected state.
Expected one of: PersistedSurfaceState.active, PersistedSurfaceState.released
But was: PersistedSurfaceState.pendingRetention

**Comment by chentianxin** [comment]
Using the examples in the demo(https://github.com/RafaelBarbosatec/tutorial_coach_mark/tree/master/example) to test will also report errors
flutter version: 1.22.1
chrome version: 86.0.4240.75

**Comment by Easycatchup** [comment]
I can confirm this, I have the same issue. It works like a charm on Android but will totally crash the Flutter Web app.

**Comment by marcschw** [comment]
I can confirm this, I have the same issue. It works like a charm on Android but will totally crash the Flutter Web app.

**Comment by RafaelBarbosatec** [comment]
This package does not really support Flutter Web due to the use of BlendMode.clear

**Comment by jefrisingh** [comment]
When we can expect?
