### ISSUE TITLE
Finish method is called on switching tabs

### ISSUE THREAD

**Issue by AkankshaKS** [RafaelBarbosatec/tutorial_coach_mark#43]
I have 4 tabs in my app, in which second tab is selected by default. I need to show coach mark on second, then first tab, I have provided keys accordingly but as soon as I switch tab, finish method is being called. Is there any solution to this?

**Comment by ycv005** [comment]
Have you tried with the Indexed Stack ?. Note- I am not the plugin's developer.

**Comment by AkankshaKS** [comment]
Thanks for suggestion @ycv005 , Do you mean using Indexed stack for tabs or coach mark, Since we add our respective targets by defining key and widget in initTarget method.

**Comment by ycv005** [comment]
1- Set a Global variable across whole app which keep track of your current tutorial.
2- In build of second tab, set a condition if tutorial number is 2 then show tutorial. So when you switch tab, build will be called and if condition is met, tutorial will be shown.

**Comment by RafaelBarbosatec** [comment]
ycy005's suggestion solves the doubt. If the problem persists, reopen the issue.
