### ISSUE TITLE
How to close tutorial_coach_mark when you run already.

### ISSUE THREAD

**Issue by chhumsovann** [RafaelBarbosatec/tutorial_coach_mark#44]
Hello! I have some problems. I want to show tutorial_coach_mark only one time when I open the app first and then close. I don't want to show it again and again. How to do it? please give me an example. Thank you

**Comment by RafaelBarbosatec** [comment]
Hi @chhumsovann ! 
You can use some kind of persistence like the `shared_preferences` package to save if the tutorial has already occurred. And then always consult this to decide whether or not to show the tutorial

**Comment by nisargpro** [comment]
is there any code example for this package?
