### ISSUE TITLE
Stop Animation

### ISSUE THREAD

**Issue by Abdox3** [RafaelBarbosatec/tutorial_coach_mark#54]
I am using Lottie animated icons it would be great if I can stop the animation of the overlay

**Comment by Avadhoot5296** [comment]
you can use **Tween(begin:1,end:1)** to disable pulsating animation @Abdox3

**Comment by RafaelBarbosatec** [comment]
Great @Avadhoot5296  and set `focusAnimationDuration` Duration.zero.
