### ISSUE TITLE
Get next target on full screen tap

### ISSUE THREAD

**Issue by saveKenny** [RafaelBarbosatec/tutorial_coach_mark#59]
I think tutorial_coach_mark is a great tool, the best out there. My problem is that I can get the next target only if I'm pressing on a free space on the screen.

In my case I have many texts on the tutorial, so users are very struggling to next each target.

Is there a way to tell the TutorialCoachMark to go the next target? So users will be able to tap on the entire screen in order to get the next target.

Thanks!

**Comment by jain-aayush1123** [comment]
I am also facing the same issue. Did u find a workaround?

**Comment by saveKenny** [comment]
Nothing so far 😕

**Comment by saveKenny** [comment]
> I am also facing the same issue. Did u find a workaround?

Nothing so far 😕

**Comment by patelnirav48** [comment]
Set enableOverlayTab: true in your TargetContent it will allow you to move to next target by clicking on whole screen overlay

**Comment by saveKenny** [comment]
@patelnirav48 @RafaelBarbosatec That's just not true. You cannot press on a screen with widgets (checkout my question).

Try it yourself!

**Comment by RafaelBarbosatec** [comment]
I will check again.

**Comment by RafaelBarbosatec** [comment]
Hi @saveKenny !
What must be happening is that you are clicking on the widget that you put to display above the overlay.
To solve this, add an IgnorePoint above the widget you pass in TargetContent.

**Comment by saveKenny** [comment]
> Hi @saveKenny !
> What must be happening is that you are clicking on the widget that you put to display above the overlay.
> To solve this, add an `IgnorePoint` above the widget you pass in `TargetContent`.
> And don’t forget `enableOverlayTab: true` in `TargetFocus`

Solved my issue! Thanks @RafaelBarbosatec !
