### ISSUE TITLE
【bug】: The distance of AlignContent.bottom  is not calculated correctly

### ISSUE THREAD

**Issue by fantasy525** [RafaelBarbosatec/tutorial_coach_mark#6]
@RafaelBarbosatec Hi,I found a bug？
I don't understand why you're doing this
tutorial_coach_mark_widget.dart
- 1
```dart

    var positioned = Offset(target.offset.dx + target.size.width / 2,
        target.offset.dy + target.size.height / 2);
```
- 2
```dart
    var sizeCircle = target.size.width > target.size.height
        ? target.size.width
        : target.size.height;
```
- 3
```dart
   sizeCircle = sizeCircle * 0.6 + widget.paddingFocus;
```

All the above steps cause the calculated top value to be too large,and `ContentTarget`widget is far away from `TargetFoucs`widget,they should be close
```dart
 case AlignContent.bottom:
          {
            weight = MediaQuery.of(context).size.width;
            left = 0;
            top = positioned.dy + sizeCircle; // it's too large
            bottom = null;
          }
          break;
```

and IImade changes to each of the above steps
- 1
```dart
 var positioned = Offset(target.offset.dx + target.size.width / 2,
        target.offset.dy);
```
- 2
```dart
    var sizeCircle = target.size.width > target.size.height
        ? target.size.height
        : target.size.width;
```
- 3
```dart
//    sizeCircle = sizeCircle * 0.6 + widget.paddingFocus;
```

**Comment by RafaelBarbosatec** [comment]
I had no problem so far. I already used it in 3 projects and I did not have this problem, besides the people that I certainly already used.
But all contributions are welcome. If possible open a Pull request with these modifications, I will evaluate.

**Comment by Vanethos** [comment]
Hey there!

Before seeing this issue I was in the process of fixing it.

In my case, I'm not using the target shape `Circle`, so when using it on rectangular widgets the content would be too far off.

The PR fixes that by calculating in a different way the offset for the circle and the rectangular shape
