### ISSUE TITLE
Migrate to null safety?

### ISSUE THREAD

**Issue by EducatedDeer** [RafaelBarbosatec/tutorial_coach_mark#64]
When will the package migrate to null safety?

Pull request is ready as far as i can see.

**Comment by jaumard** [comment]
What's the status here @RafaelBarbosatec ? a PR is open for that :)

**Comment by RafaelBarbosatec** [comment]
Hi guys! Thanks for issue.
I will be evaluating PR today.

**Comment by RafaelBarbosatec** [comment]
Available in 1.0.0 version
