### ISSUE TITLE
Feature: Option to animate the text/title only without changing focus

### ISSUE THREAD

**Issue by CaptainDario** [RafaelBarbosatec/tutorial_coach_mark#65]
In my app some buttons have different behaviors depending on the way they are pressed.
Pressing is different from double tapping or long pressing etc..

To show the different ways of using them I am currently showcasing the same element multiple times.
This results in the vignette zooming in and out.
However it would be nice to have an option to only fade in and out the text.

Here is a video to show what I mean:
<img src="https://user-images.githubusercontent.com/51273483/113558637-4f53f200-9600-11eb-9535-503dd6cc8436.gif" alt="drawing" width="200"/>

**Comment by RafaelBarbosatec** [comment]
Hi @CaptainDario 
I got it. Very interesting point. but I think at the moment it would be kind of complicated to implement that. I think a solution would be for you to put all the texts at the top, which has a lot of space.
