### ISSUE TITLE
Feature request: Handle orientation change

### ISSUE THREAD

**Issue by w3ggy** [RafaelBarbosatec/tutorial_coach_mark#66]
Right now during the tutorial, you can't rotate the device because at least `_targetPosition` in the `AnimatedFocusLight` stateful widget updates only after startup or changing the current tutorial page. This item contains the size of the focused widget and renders it correctly. 

I didn't find an easy way to fix it on production.

**Comment by RafaelBarbosatec** [comment]
So this really is a problem. I don't have in mind how to solve this for now. This package does not support screen rotation at the time the tutorial started. I recommend you lock the screen rotation in the tutorial.
