### ISSUE TITLE
Run tutorial only after the page transition animation ends

### ISSUE THREAD

**Issue by lsribeiro** [RafaelBarbosatec/tutorial_coach_mark#67]
While trying to start a tutorial right when a user enters a screen, I've been having the following issue: The tutorial sometimes starts before the page transition animation ends. As a result, the targets end up not highlighting the widgets at their correct position.

I've tried adding a delay before running the tutorial, but the tutorial doesn't start if the length of the delay is too long.

Any help would be appreciated!

**Comment by newcaiosantos** [comment]
Same problem here.

This workaround worked for me, but it not seems to be the best solution:

```
    Future.delayed(Duration(seconds: 1), () {
      budgetButtonCoachMark.show();
    });
```
