### ISSUE TITLE
How can I implement tutorial Coach Mark over several Widgets?

### ISSUE THREAD

**Issue by corusm** [RafaelBarbosatec/tutorial_coach_mark#69]
I have multiple Stateless and Statefull widgets. I wan't to make the tutorial Coach with one button over multiple Files.
Is there a way to pass the Globalkeys oder is there another Method?

**Comment by RafaelBarbosatec** [comment]
Hi @corusm !
In the moment is not possible to focus in multiple targets.
If it's available, and want to contribute a PR by adding this new feature, it would be great!

**Comment by SalahAdDin** [comment]
> Hi @corusm !
> In the moment is not possible to focus in multiple targets.
> If it's available, and want to contribute a PR by adding this new feature, it would be great!

I thought it could be possible since the `GlobalKey` is a value across multiple widgets, may am i wrong?

**Comment by desmeit** [comment]
@SalahAdDin 
for me this is working, thanks.

**Comment by kutsarenko** [comment]
> @SalahAdDin for me this is working, thanks.
> 
> Edit: after several more tests, unfortunately, it is not possible to do it this way. I always get "duplicate Global Key".

I get the same error. Do you have any update with the issue?

**Comment by SalahAdDin** [comment]
> > @SalahAdDin for me this is working, thanks.
> > Edit: After several more tests, unfortunately, it is not possible to do it this way. I always get "duplicate Global Key".
> 
> I get the same error. Do you have any updates on the issue?

No idea about it.

**Comment by CengizhanParlak** [comment]
I had this issue too, the problem was, I was adding `GlobalKey` to a list element, which then created like 100 more. All I needed to do was ensure the only first element of the list gets the key. Like:
```dart
ListView.builder(
...
    key: index == 0 ? keyButton1 : null,
...
),
```

**Comment by PratikKmp** [comment]
I/flutter (17409): FormatException: It was not possible to obtain target position (Target 2).
I/flutter (17409): finish
