### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by volgin** [RafaelBarbosatec/tutorial_coach_mark#70]
i get the following error in a fully null-safe app.

```
_CastError
Null check operator used on a null value

tutorial_coach_mark.dart in TutorialCoachMark.show.<fn>.<fn> at line 79 within tutorial_coach_mark

```

**Comment by RafaelBarbosatec** [comment]
HI @volgin !
I could not reproduce this error. You can give me more information about flutter version, code, etc?

**Comment by raunak-moonraft** [comment]
@RafaelBarbosatec 
This same issue is happening with me as well. We are using tutorial_coach_mark: ^1.0.3 (the latest version at present). Here is the crashlytics issue: -

Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value. Error thrown null.
       at TutorialCoachMark.show.<fn>(tutorial_coach_mark.dart:80)
       at _CustomZone.bindCallback.<fn>(dart:async)
       at TickerFuture.whenCompleteOrCancel.thunk(ticker.dart:407)

Device OS Android 11
