### ISSUE TITLE
Assign next target and skip fucntions to a widget.

### ISSUE THREAD

**Issue by juanp88** [RafaelBarbosatec/tutorial_coach_mark#73]
Hi, the package is awsome but I was wondering if there is a way to go to the next target by touching button in a widget on the overlay and not the target itself something like this:

![image](https://user-images.githubusercontent.com/23729744/121753789-b3030b80-cad8-11eb-944e-be0db9861469.png)

also, following that line of thought, would be possible to skip the tutorial by touching some other button on the widget?

**Comment by RafaelBarbosatec** [comment]
Hi @juanp88 !
Thanks for the compliments! 😊
So, Actually it’s not possible. I'll think about it.
I'll keep this issue open to think a solution for this.

**Comment by RafaelBarbosatec** [comment]
In  1.0.3 version You can create a widget in `TargetContent` with `builder`. This way you will can have access the a controller.
