### ISSUE TITLE
Edit the "opening" animation duration.

### ISSUE THREAD

**Issue by SalahAdDin** [RafaelBarbosatec/tutorial_coach_mark#75]
Hi, 

We are using your package to introduce our application to our clients and it is really cool.

We see the animation triggered once you click on the **TargetFocus** widget closes really fast, it would be great if it takes some time after opening the circle and closing it too, or maybe, to make this animation slower.

Thank you.

**Comment by RafaelBarbosatec** [comment]
You can edit this duration using the param of the `TutorialCoachMark`:
```dart
focusAnimationDuration: Duration(),
```
