### ISSUE TITLE
Should `finish()` be called when we skip the tutorial?

### ISSUE THREAD

**Issue by Vanethos** [RafaelBarbosatec/tutorial_coach_mark#8]
The `finish()` callback is called both when we see the tutorial and when we skip it.

What if we want some code to be called *if* we skip the tutorial *else* execute the code that we want if the user sees it all through?

My proposal is to have 3 callbacks:

- `dispose()` - to be called when the widget is going to be destroyed, in this case it can be the code for `hide()`
- `clickSkip()` or `skipCallback()` - to be called when the user skips the tutorial
- `onTutorialFinish()` (naming can change) - to be called when the user sees through the tutorial

This way, we can have common code between the state `SKIP` and `NOT SKIP` via `dispose`, and custom callbacks for both situations.

**Comment by RafaelBarbosatec** [comment]
Bug fixed
