### ISSUE TITLE
TutorialCoachMark overlaps a new instance in hot reaload.

### ISSUE THREAD

**Issue by SalahAdDin** [RafaelBarbosatec/tutorial_coach_mark#80]
Hello,

Thanks for your help to us with any ew issue.

We have been suffering an overlapping problem with hot realoading:
![image](https://user-images.githubusercontent.com/5034215/128392229-65f3503b-9558-4799-870d-e48330ff767f.png)

It happends when there is a change on `TargetFocus` widgets most of the time and at hot realoading it just creates a new instance of the coach which overlaps the existing one.

Why does this happen?

**Comment by nmazidi** [comment]
Any updates on this? Thanks

**Comment by ashkryab-fl** [comment]
save tutorial instance and show again if u need

 if (tutorials.first.instanse != null) {
    tutorials.first.instanse.show();
    return;
  }
  var tutorial = TutorialCoachMark(context,.......

**Comment by ashkryab-fl** [comment]
call setState after calling "show()"

**Comment by SalahAdDin** [comment]
> call setState after calling "show()"

Can you share a gist or a full piece of code?

Thanks.
