### ISSUE TITLE
how to resize the circle overlay?

### ISSUE THREAD

**Issue by eggysudianto** [RafaelBarbosatec/tutorial_coach_mark#98]
how to resize the circle overlay? because my circle is have a large padding

**Comment by Tughra** [comment]
You can decrease size of circle changing the "paddingFocus:0".

`  targets.add(
      TargetFocus(
        identify: "keyBottom5",
        keyTarget: keyButton5,
        paddingFocus: 0,
        shape: ShapeLightFocus.RRect,radius: 10,
        alignSkip: Alignment.topRight,
        contents: [
          TargetContent(
            align: ContentAlign.bottom,
            builder: (context, controller) {
              return Container(alignment: Alignment.topCenter,
                child: Column(
                  mainAxisSize: MainAxisSize.max,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: <Widget>[
                    Text(
                      "Gelen bildirimleri buraya tıklayarak görüntüleyebilirsiniz.",
                      style: TextStyle(
                        color: Colors.white,
                      ),
                    ),
                  ],
                ),
              );
            },
          ),
        ],
      ),
    );`
